name: ci
on:
  push:
  workflow_dispatch:
    inputs:
      run_tests:
        description: "Run tests"
        default: false
        required: false
        type: boolean
      run_additional_tests:
        description: "Run additional tests"
        default: false
        required: false
        type: boolean
      build_e2e_tests:
        description: "Build end-to-end tests"
        default: false
        required: false
        type: boolean
      build_app:
        description: "Build app"
        default: false
        required: false
        type: boolean
      build_docs:
        description: "Build docs"
        default: false
        required: false
        type: boolean

jobs:
  run_tests:
    name: Run tests
    if: ${{
      github.event_name == 'workflow_dispatch' && inputs.run_tests ||
      github.event_name == 'push' && !contains(github.event.head_commit.message, 'skip tests')
      }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Restore Yarn cache
        uses: actions/cache@v4
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Init runner
        run: bash ./scripts/init_runner.sh ${{ github.job }}

      - name: Setup workspace
        env:
          KALISIO_GITHUB_URL: ${{ secrets.KALISIO_GITHUB_URL }}
        run: bash ./scripts/setup_workspace.sh -k klifull

      - name: Save Yarn cache
        uses: actions/cache@v4
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Run tests
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        run: bash ./scripts/run_tests.sh -c -r ${{ github.job }}

  additional_tests:
    strategy:
      fail-fast: false
      matrix:
        node: [22]
        mongo: [7]
    name: Additional tests
    if: ${{
      github.event_name == 'workflow_dispatch' && inputs.run_additional_tests ||
      github.event_name == 'push' && contains(github.event.head_commit.message, 'additional tests')
      }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Restore Yarn cache
        uses: actions/cache@v4
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Init runner
        run: bash ./scripts/init_runner.sh ${{ github.job }}

      - name: Setup workspace
        env:
          KALISIO_GITHUB_URL: ${{ secrets.KALISIO_GITHUB_URL }}
        run: bash ./scripts/setup_workspace.sh -k klifull -n ${{ matrix.node }}

      - name: Save Yarn cache
        uses: actions/cache@v4
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Run tests
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        run: bash ./scripts/run_tests.sh -n ${{ matrix.node }} -m ${{ matrix.mongo }}
